SECRET_KEY = 'secretkey'
SQLALCHEMY_DATABASE_URI = 'sqlite:///app.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
DEBUG = True
TESTING = False
REMEMBER_COOKIE_SAMESITE = "None"
REMEMBER_COOKIE_SECURE = True
WTF_CSRF_ENABLED = False